const menu = [
  ["Normas Generales", "/normativa/generales"],
  ["Términos y Condiciones", "/normativa/terminos"],
  ["Normas EMS / SURA", "/normativa/sura"],
  ["Normas Facciones", "/normativa/facciones"],
  ["Normas Mecánico", "/normativa/mecanico"],
  ["Normas Policiales", "/normativa/tombos"],
  ["Normas Ilegales", "/normativa/ilegales"],
  ["Normas Alcaldía", "/normativa/alcaldia"],
  ["Normas RCN Televisión", "/normativa/rcntele"],
  ["Normas Prosegur", "/normativa/prosegur"],
  ["Sanciones", "/normativa/sanciones"],
  ["Donaciones", "/normativa/donaciones"],
  ["Normas Tránsito", "/normativa/transito"],
  ["Normas Streamers", "/normativa/streamers"],
];
