const menu = [
  ["Normas Generales", "/normativa/generales"],
  ["Términos y Condiciones", "/normativa/terminos"],
  ["Normas EMS", "/normativa/sura"],
  ["Normas Facciones / Negocios", "/normativa/facciones"],
  ["Normas Mecánico", "/normativa/mecanico"],
  ["Normas Tombos", "/normativa/tombos"],
  ["Normas Ilegales", "/normativa/ilegales"],
  ["Normas Alcaldía", "/normativa/alcaldia"],
  ["Normas RCN", "/normativa/rcn"],
  ["Normas Sociales", "/normativa/sociales"],
  ["Normas de Seguridad", "/normativa/seguridad"],
  ["Sanciones", "/normativa/sanciones"],
  ["Donaciones", "/normativa/donaciones"],
  ["Multas de Donaciones", "/normativa/multas"],
  ["Creadores de Contenido", "/normativa/creadores"],
];
